Navbar fixed and responsive nabber added
ethan-master-coding/My-work pull request #7
Opened 2022-07-25 14:32 UTC by seymourjr5

Navbar fixed and responsive nabber added 
![Screenshot 2022-07-25 at 15 26 27](https://user-images.githubusercontent.com/87953328/180801977-60b4d503-e190-428b-9edb-bd6a20e2ef13.png)
![Screenshot 2022-07-25 at 15 26 36](https://user-images.githubusercontent.com/87953328/180802013-7e954e34-a9ed-4748-8cdf-3fec505d000e.png)
**Small Screens**
![Screenshot 2022-07-25 at 15 27 06](https://user-images.githubusercontent.com/87953328/180802140-40591e7c-3aca-4670-af54-5564b75d143a.png)
![Screenshot 2022-07-25 at 15 27 18](https://user-images.githubusercontent.com/87953328/180802165-08c99e27-d4d7-48e6-ba53-d8073f26a1fa.png)

2022-07-26 01:00 UTC, ethan-master-coding requested changes
I like the changes. On desktop when the nav bar is collapsed I would prefer that the icons still display like it is currently.

2022-07-26 01:00 UTC, ethan-master-coding commented on globle.css
> +@media only screen and (max-width: 768px){
```suggestion
@media only screen and (max-width: 580px){
```

2022-07-26 01:00 UTC, ethan-master-coding commented on Contact.html
> +    <meta name="description" content="Project">
```suggestion
```

Already have a description on line 7

2022-07-26 01:00 UTC, ethan-master-coding commented on index.html
> +    <meta name="description" content="Project">
```suggestion
```

Already have a description on line 5

2022-07-26 09:26 UTC, seymourjr5 commented
I have changed the nav bar on desktop as you suggested 
![Screenshot 2022-07-26 at 10 18 00](https://user-images.githubusercontent.com/87953328/180972816-86051f81-9aef-4570-9c8b-38abdc3ea9f4.png)
![Screenshot 2022-07-26 at 10 18 08](https://user-images.githubusercontent.com/87953328/180972877-c15bd6dc-3bb9-45e6-b155-5384cc80de1f.png)
**on hover**
![Screenshot 2022-07-26 at 10 18 24](https://user-images.githubusercontent.com/87953328/180973007-d2c83773-db70-462f-9826-fa31634a9b76.png)

2022-07-27 02:51 UTC, ethan-master-coding commented
Got a few more suggestions before we merge. Mostly just change the links from relative ones to absolute ones to keep it consistent.

2022-07-27 02:51 UTC, ethan-master-coding commented on Projects.html
> +        <div class="nav-item"><a href="./index.html"><i class="fas fa-home links" id="nav-logo"></i> <span class="nav-text">Home</span></a></div>
```suggestion
        <div class="nav-item"><a href="https://ethan-master-coding.github.io/My-work/"><i class="fas fa-home links" id="nav-logo"></i> <span class="nav-text">Home</span></a></div>

```

2022-07-27 02:51 UTC, ethan-master-coding commented on Projects.html
> +        <div class="nav-item"><a href="./Projects.html"><i class="fas fa-project-diagram links" id="nav-logo"></i> <span class="nav-text">Projects</span></a></div>
```suggestion
        <div class="nav-item"><a href="https://ethan-master-coding.github.io/My-work/Projects"><i class="fas fa-project-diagram links" id="nav-logo"></i> <span class="nav-text">Projects</span></a></div>

```

2022-07-27 02:51 UTC, ethan-master-coding commented on Projects.html
> +        <div class="nav-item"><a href="./Contact.html"><i class="fas fa-id-card-alt links"></i> <span class="nav-text">Contact</span></a></div>
```suggestion
        <div class="nav-item"><a href="https://ethan-master-coding.github.io/My-work/Contact"><i class="fas fa-id-card-alt links"></i> <span class="nav-text">Contact</span></a></div>

```

2022-07-27 02:51 UTC, ethan-master-coding commented on Projects.html
> +      <a href="./index.html"><i class="fas fa-home" id="nav-logo"></i> Home</a>
```suggestion
      <a href="https://ethan-master-coding.github.io/My-work/"><i class="fas fa-home" id="nav-logo"></i> Home</a>
```

2022-07-27 02:51 UTC, ethan-master-coding commented on Projects.html
> +      <a href="./Projects.html"><i class="fas fa-project-diagram" id="nav-logo"></i> Projects</a>
```suggestion
      <a href="https://ethan-master-coding.github.io/My-work/Projects"><i class="fas fa-project-diagram" id="nav-logo"></i> Projects</a>
```

2022-07-27 02:51 UTC, ethan-master-coding commented on Projects.html
> +      <a href="./Contact.html"><i class="fas fa-id-card-alt"></i> Contact</a>
```suggestion
      <a href="https://ethan-master-coding.github.io/My-work/Contact"><i class="fas fa-id-card-alt"></i> Contact</a>
```

2022-07-27 02:51 UTC, ethan-master-coding commented on index.html
> +        <div class="nav-item"><a href="./Contact.html"><i class="fas fa-id-card-alt links"></i> <span class="nav-text">Contact</span></a></div>
```suggestion
        <div class="nav-item"><a href="https://ethan-master-coding.github.io/My-work/Contact"><i class="fas fa-id-card-alt links"></i> <span class="nav-text">Contact</span></a></div>
```

2022-07-27 02:51 UTC, ethan-master-coding commented on index.html
> +      <a href="./index.html"><i class="fas fa-home" id="nav-logo"></i> Home</a>
```suggestion
      <a href="https://ethan-master-coding.github.io/My-work/"><i class="fas fa-home" id="nav-logo"></i> Home</a>
```

2022-07-27 02:51 UTC, ethan-master-coding commented on index.html
> +      <a href="./Projects.html"><i class="fas fa-project-diagram" id="nav-logo"></i> Projects</a>
```suggestion
      <a href="https://ethan-master-coding.github.io/My-work/Projects"><i class="fas fa-project-diagram" id="nav-logo"></i> Projects</a>
```

2022-07-27 02:51 UTC, ethan-master-coding commented on index.html
> +      <a href="./Contact.html"><i class="fas fa-id-card-alt"></i> Contact</a>
```suggestion
      <a href="https://ethan-master-coding.github.io/My-work/Contact"><i class="fas fa-id-card-alt"></i> Contact</a>
```

2022-07-28 10:10 UTC, seymourjr5 commented
Should be ready to merge, I double checked everything, should work perfectly.

2022-07-28 11:35 UTC, ethan-master-coding commented
@seymourjr5 before we merge I want to check the changed locally to make sure nothing broke. I will do that later.

2022-07-28 12:11 UTC, ethan-master-coding approved these changes
Just checked and we did not brake anything.

2022-07-28 12:11 UTC, merged